### ISSUE TITLE
Import cover: Cedar Creek Trait 2016-2020

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#157]

**Comment by KW529** [comment]
Hi Forest,

I hope all is well! I have a question about your biomass vs cover subplots. It looks like for each of the 60 plots you collected biomass in one of the following subplots: 'Middle', 'North', or 'South'. On the other hand, for each plot you estimated cover in all subplots 'Middle', 'North', and 'South'. I am guessing that I should average cover across 'Middle', 'North', and 'South' subplots within each plot. However, I wanted to check that these subplots don't represent something different since biomass was collected in one subplot where you all also estimated cover for each plot.

Thanks so much for clarification on this!

Best,
Kate Wilkins

**Comment by KW529** [comment]
Hi Kate,

Good question. This experiment has a nested split-plot design. Main plots are 9 by 9 m in size. This is the spatial scale at which the non-drought treatments (fertilization and irrigation) were randomized. The three drought treatments (no shelter, shelter, infrastructure control) are randomized to subplots, which are 3 by 3 m in size and which are named according to their positions in the plot (North, Middle, South). Thus, if you are only considering the drought treatment effects, then the subplots will correspond to what other DroughtNet sites will be calling plots. In other words, the degrees of freedom for testing drought effects should reflect the number of subplots, rather than the number of plots. We should not average across the subplots. Does this make sense? If not, then I am happy to elaborate or send a diagram, if that would be helpful.

Best wishes,

Forest

**Comment by KW529** [comment]
Hi Forest,

Thanks so much for this clarification! It sounds like for the cover data I need to relabel the plots for our database to reflect that each subplot represents a plot.

Best, 

Kate Wilkins

**Comment by KW529** [comment]
Hi Kate,

Yes, I believe that would make sense for comparability with other studies. Perhaps 'subplot' could be renamed 'plot' and what I had listed as 'plot' could become 'main.plot' or something similar as a reminder that it is a larger spatial scale.

Best wishes,

Forest

**Comment by KW529** [comment]
Thanks, Peter! Also, have you ever had a site lump the cover for mosses and lichens together? If so, how do you all handle this? (Cedar Trait lumped mosses and lichens together)

**Comment by KW529** [comment]
Cover for moss and lichen is a little tricky. Most sites don't report it, the next lump of sites reports it as a ground cover value (like bare ground, rock, litter, bryophyte, etc), and a small fraction of sites (mostly the Scandinavian ones) ID species of moss and lichen and report them like any other species.

So, ignoring that last group, I just kind of package it together as bryophytes and assume most people won't use those in diversity calculations. The sites that do report species I kind of feel like I should hide from the output, since it's not an unbiased diversity measurement since most people don't distinguish.

Short answer: I'd just connect it to the 'BRYOPHYTE' taxon in the taxon table and not worry about it.

Peter

**Comment by KW529** [comment]
LUMPING joint 'Mosses and Lichens' category into bryophytes.

**Comment by KW529** [comment]
Hi Forest,

In reviewing your cover data for Cedar Creek Trait, you have duplicates for the following species in a plot and subplot for 2016:

site | plot | subplot | taxa | cover | date
-- | -- | -- | -- | -- | --
Cedar Creek tIDE | 39 | North | Liatris_aspera | 18 | 25-Aug-16
Cedar Creek tIDE | 39 | North | Liatris_aspera | 9 | 25-Aug-16
Cedar Creek tIDE | 49 | North | Andropogon_gerardi | 3 | 25-Aug-16
Cedar Creek tIDE | 49 | North | Andropogon_gerardi | 2 | 25-Aug-16
Cedar Creek tIDE | 49 | North | Panicum_oligosanthes | 3 | 25-Aug-16
Cedar Creek tIDE | 49 | North | Panicum_oligosanthes | 4 | 25-Aug-16
Cedar Creek tIDE | 49 | North | Petalostemum_purpureum | 12 | 25-Aug-16
Cedar Creek tIDE | 49 | North | Petalostemum_purpureum | 9 | 25-Aug-16
Cedar Creek tIDE | 49 | North | Petalostemum_villosum | 7 | 25-Aug-16
Cedar Creek tIDE | 49 | North | Petalostemum_villosum | 6 | 25-Aug-16
Cedar Creek tIDE | 49 | North | Schizachyrium_scoparium | 13 | 25-Aug-16
Cedar Creek tIDE | 49 | North | Schizachyrium_scoparium | 9 | 25-Aug-16
Cedar Creek tIDE | 49 | North | Solidago_nemoralis | 19 | 25-Aug-16
Cedar Creek tIDE | 49 | North | Solidago_nemoralis | 19 | 25-Aug-16
Cedar Creek tIDE | 214 | North | Petalostemum_purpureum | 3 | 29-Aug-16
Cedar Creek tIDE | 214 | North | Petalostemum_purpureum | 2 | 29-Aug-16
Cedar Creek tIDE | 309 | North | Lupinus_perennis | 1 | 31-Aug-16
Cedar Creek tIDE | 309 | North | Lupinus_perennis | 3 | 31-Aug-16

**Comment by KW529** [comment]
E-mail from Forest (11-10-2021):

Hi Kate,

I have now gone back to the original data and can confirm that these are all cases where duplicate measurements were made on the same species. Thus, for most questions, I suspect it will be best to average these multiple values for a species within a plot.

Best wishes,

Forest

**Comment by nutnetadmin** [comment]
Uploaded with 'import-cedar-creek-trait-cover-2016-2020.sql'
