### ISSUE TITLE
Import cover: Santa Cruz Low 2015

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#190]

**Comment by KW529** [comment]
E-mail sent to Michael (07-14-2020):

"Hi Michael,

I hope this email finds you in good health! I am e-mailing to double check the cover values you submitted for the Santa Cruz sites (Low, Middle, and High). It looks like all the values are below 1 (0.90, 0.80, 0.02, etc.). I just want to make sure that I should multiply these values by 100 to get the percent cover. Thanks so much for any clarification on this!

Best,
Kate"

**Comment by KW529** [comment]
Michael's reply (07-16-2020):

"Hi Kate,

Yes, that appears to be correct. I just looked at the metadata and noted it should have been entered as 0-100. Sorry about that. I will make sure that we correct that for the future.

I hope you are doing well.

Thanks, and Best regards,
Michael"

**Comment by kristenpeach** [comment]
Finished. It seems like once you complete 1 year from a single site the other years for that site are quite easy. Again, let me know if there are any problems here. I will be switching back to other projects tomorrow (until Monday) which should give you some time to review what I have done to see if there are any red flags.
