### ISSUE TITLE
Import cover: Santa Cruz Low 2016

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#193]

**Comment by kristenpeach** [comment]
Hi Kate, 

Questions:
1. I am having some trouble with this check: # does cover correspond to plan_temp and plots/subplots in database? 
The cover_temp_kp table includes 10 plots but the plan_temp_kp table only includes 5 plots. 

2. Should cover values be reported as whole numbers with no decimal points? For example, '12' or '12.00' or '12.0'?

**Comment by KW529** [comment]
Hi Kristen,

I have some time to meet to discuss this tomorrow. Is there a time that works best for you?

Best,
Kate

PhD, Ecology
Postdoctoral Fellow
Department of Biology
Colorado State University
e-mail: kate.wilkins@colostate.edu
website: http://kate-wilkins.weebly.com/
phone: 713-819-1198
________________________________

**Comment by kristenpeach** [comment]
Hi Kate,

Anytime after 1pm Pacific time works for me.

Best,

Kristen Peach, PhD
National Center for Ecological Analysis and Synthesis
University of California
735 State Street, Suite 300
Santa Barbara, CA 93101-3351
kristenpeach1@gmail.com
peach@nceas.ucsb.edu
pronouns: she/her

**Comment by KW529** [comment]
Hi Kristen,

Would 2:30 pm Mountain (1:30 pm Pacific) work for you?

Best,
Kate

PhD, Ecology
Postdoctoral Fellow
Department of Biology
Colorado State University
e-mail: kate.wilkins@colostate.edu
website: http://kate-wilkins.weebly.com/
phone: 713-819-1198
________________________________

**Comment by kristenpeach** [comment]
Sounds good!

Kristen Peach, PhD
National Center for Ecological Analysis and Synthesis
University of California
735 State Street, Suite 300
Santa Barbara, CA 93101-3351
kristenpeach1@gmail.com
peach@nceas.ucsb.edu
pronouns: she/her

**Comment by kristenpeach** [comment]
**Progress**

Made adjustments we talked about on the call and now it's looking good. I will check in with you before I commit final changes tomorrow or Monday. Thank you so much for the zoom that was so helpful!

**Comment by kristenpeach** [comment]
Hi Kate,

Quick question:
Is 'caespitose' an acceptable entry for provenance? I thought that was more of a growth form (growing in tufts or mounds) than a provenance. It is only shown in the table for Avena barbara which is a non-native grass. 

Thanks!
Kris

**Comment by KW529** [comment]
Hi Kristin,

Great that you're making progress, and I'm glad I was helpful! Caespitose would not work for provenance. The only acceptable entries are Introduced (INT), Native (NAT), or Unknown (UNK).

Best,
Kate

PhD, Ecology
Postdoctoral Fellow
Department of Biology
Colorado State University
e-mail: kate.wilkins@colostate.edu
website: http://kate-wilkins.weebly.com/
phone: 713-819-1198
________________________________

**Comment by kristenpeach** [comment]
Ok great. I removed caespitose and replaced it with NA. 

One more quick question: 

Why does the output from the Rcode include"IGNORE" before INTO? I see that it does this in the recording from your demo as well. Do I run these lines with IGNORE or do I remove it?

**Example:** 

**Code output from R:**
INSERT IGNORE INTO higher_taxonomy (Ordr, Family, Genus) select distinct Ordr, Family, 'BROMUS' from higher_taxonomy where Family='Poaceae';

**Code from example sql script:**
INSERT INTO higher_taxonomy (Ordr, Family, Genus) select distinct Ordr, Family, 'CRYPTANTHA' from higher_taxonomy where Family='Boraginaceae';

Also, would you mind sharing the recording from our second training session? You were the host for that one so you recorded. 

Thank you!

**Comment by KW529** [comment]
Hi Kristen,

Great question. Also, for that one species, could you look it up to see if it's native? For singular species like that, I usually search on the Internet to see how to designate them. Also, the IGNORE is there so that we don't upload duplicates. Thus, it will IGNORE your entry if it's already there.

Best,
Kate

PhD, Ecology
Postdoctoral Fellow
Department of Biology
Colorado State University
e-mail: kate.wilkins@colostate.edu
website: http://kate-wilkins.weebly.com/
phone: 713-819-1198
________________________________

**Comment by kristenpeach** [comment]
Hi Kate, 

Ok I need to switch to a different project now. I did not quite finish up this script but I am pretty close. It would be very helpful to have the recording of the second half of the training we did so I can finish when I return to this project on Monday. 

Thanks!
Kris

**Comment by KW529** [comment]
Hi Kristen,

Awesome- thanks so much! Please follow this link to the video: [https://r3.res.outlook.com/owa/prem/images/video_16x16.png] zoom_0.mp4<https://colostate-my.sharepoint.com/:v:/g/personal/kwilks86_colostate_edu/EWvPvlhxNeVLgjy-h5QR1A0B0VDzbk3KLUfAivVqBM98Zg?e=jdaijs>

Best,
Kate

PhD, Ecology
Postdoctoral Fellow
Department of Biology
Colorado State University
e-mail: kate.wilkins@colostate.edu
website: http://kate-wilkins.weebly.com/
phone: 713-819-1198
________________________________

**Comment by kristenpeach** [comment]
Hi Kate, 

In the taxa info there is a species '_Tragopogon_porriflorus_' which does not exist. I assumed that they meant to write "_Tragopogon porrifolius_" which is an accepted name according to The Plant List (http://www.theplantlist.org/tpl1.1/record/gcc-47967). But they could also have meant to write "_Tragopogon parviflorus_" which is an unresolved taxonomic name according to The Plant List. Can you check with the PI for me? Thanks!

Kris

**Comment by kristenpeach** [comment]
Hi Kate, 

I think that they meant _Tragopogon porrifolius_ so I entered that. I was confident in committing all the changes I made but feel free to check my work. If what I have done looks ok to you I will move on to Santa Cruz Low 2017. I think it will be much easier from now on.

Thanks!
Kris

**Comment by KW529** [comment]
Hi Kristen,

Thanks so much! I was going to say to check what they listed in the cover for that species or for other years. I can also double check with the PI! I also looked at what you entered, and it looks great (interesting that they don't seem to have one species in any plot that dominates- saw that the highest % cover was 49%). I think you're good to proceed!

Best,
Kate
PhD, Ecology
Postdoctoral Fellow
Department of Biology
Colorado State University
e-mail: kate.wilkins@colostate.edu
website: http://kate-wilkins.weebly.com/
phone: 713-819-1198
________________________________
