### ISSUE TITLE
Import Cover: Santa Cruz Low 2017

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#194]

**Comment by kristenpeach** [comment]
Hi Kate, 

The cover data looks a little odd for this year. For example, the first three entries are 0.04040404, 0.11111111 and 0.01265823. I know that for every year of this site I will *100 to get the cover data out of decimal format but these just seem incredibly precise. 

Other than that no problems at all with this year. I think I will be able to get through these much much faster now. 

Thanks,
Kris

**Comment by kristenpeach** [comment]
Finished! Let me know if it looks like there are any problems here. The only other oddity I will note is that all of the species in this cover data were introduced except for 1 native species (CA Poppy). I don't think that means anything is incorrect I am just noting it here.

**Comment by KW529** [comment]
Clarification e-mail sent to Michael Loik:  9-14-2020:

Hi Michael,

I have another quick question. It looks like your cover values for Santa Cruz Low in 2017 are quite precise (e.g. 45.9183673%). Are these relative cover values? There's no issue with that, but just want to make sure these numbers are correct. Thanks so much for any clarification!

Best,
Kate

**Comment by KW529** [comment]
From Michael, 9-17-2020:

Hi Kate,

Yes, relative cover. Ha, those are some interesting values. Actually, besides that, 2017 was very wet here.

Thanks for all your work pulling data together!

Best,
Michael
