### ISSUE TITLE
Import cover: Santa Cruz High 2016

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#199]

**Comment by kristenpeach** [comment]
**Progress**

Downloaded files from Dropbox and put on my desktop. Imported SantaCruzLow 2015 sql scripts. 'Saved as' Santa Cruz Low 2016 sql to my local computer (will upload to dropbox when complete). I encountered a problem with the server permissions when trying to load 'plan' csv(did not have permission to upload local files). Per Kate's request I downloaded version 6.3.1 of mySQL workbench. Imported the SantaCruzLow 2016 sql script. When I tried to run even the first few lines of code I got the spinning wheel of death and had to force quit. I restarted my computer, checked my memory availability etc but could not locate the problem. Julien is currently helping troubleshoot.
