### ISSUE TITLE
Import Cover: Santa Cruz High 2017

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#200]

**Comment by kristenpeach** [comment]
Hi Kate, 

Could you ask the PI what species they meant where they wrote 'Rumex_lstyrdead'? I reviewed the species list for Rumex and I do not have a good guess. 

Thank you!
Kris

**Comment by KW529** [comment]
Will do!

Kate Wilkins
Pronouns<https://www.mypronouns.org/what-and-why>: She/her(s)
PhD, Ecology
Postdoctoral Fellow
Department of Biology
Colorado State University
website: http://kate-wilkins.weebly.com/
phone: 713-819-1198
________________________________

**Comment by KW529** [comment]
From Michael: "That is leftover dead material of Rumex from the previous year. As in last year's dead Rumex."

I think you should be able to have a "dead" category...

Best,
Kate Wilkins
Pronouns<https://www.mypronouns.org/what-and-why>: She/her(s)
PhD, Ecology
Postdoctoral Fellow
Department of Biology
Colorado State University
website: http://kate-wilkins.weebly.com/
phone: 713-819-1198
________________________________

**Comment by kristenpeach** [comment]
So should I remove this cover data?

**Comment by KW529** [comment]
Hi Kristen,

You should include this as "Litter". There is a higher taxonomy classification for this as "Other". Let me know if you need helpe inserting this.

Kate Wilkins
Pronouns<https://www.mypronouns.org/what-and-why>: She/her(s)
PhD, Ecology
Postdoctoral Fellow
Department of Biology
Colorado State University
website: http://kate-wilkins.weebly.com/
phone: 713-819-1198
________________________________

**Comment by kristenpeach** [comment]
Done with Santa Cruz High 2017
