### ISSUE TITLE
Import biomass: Mattheis 2019

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#232]

**Comment by KW529** [comment]
Hi Baka,

Thanks again for sending the data from Kinsella and Mattheis. The 2019 Kinsella biomass looks great, however the Mattheis biomass data looks quite low compared to previous years. In your note column of the biomass tab you state, "Aboveground biomass was clipped from one 0.1 m^2 quadrat (10x100 cm in dimension) at each plot. Values were converted to biomass per meter^2 by multiplying 10. No woody biomass is included in the reported value." However, could you please double check that you all converted the 2019 Mattheis data?

Thanks!

Best,

**Comment by KW529** [comment]
Hi Kate,

I checked my raw data, and those were the converted values and matched with what I have. 

Could you please change the percent reduction of annual precipitation from 45% to 55% in the "plan" sheet? I just realized that I reported it incorrectly in there. Our rainout shelters were designed to intercept 55% of incoming rainfall. Hope this doesn't affect the analyses.

Cheers,
Baka

**Comment by KW529** [comment]
Hi Kate

Thanks for checking. There is an explanation for the low biomass,  Mattheis had below average precipitation for three years in a row (2017-2019) historical growing season precipitation for the previous 30 years is about 250 mm, while those three years averaged about 160 mm (this is my estimate, but we can get the actual values if needed).

Cheers,
Cam

**Comment by tim-ohlert** [comment]
Hi Batbaatar, James, and Cameron

We are doing data quality checks for the International Drought Experiment database and would like your input on your site  The attached figure shows average ANPP values with 95% confidence intervals for the treatment years that we have entered in our database. 



If you could please confirm that the data we have entered for your site looks correct, or if something looks incorrect let us know and we can work together to find and fix the issue.

Thanks,
Tim

**Comment by tim-ohlert** [comment]
Hi Tim,

This looks correct to me and matches with our records. Kate also asked us to check this dataset a couple of times in the past. If needed, I can forward you those emails.

Baka

**Comment by tim-ohlert** [comment]
Hi Baka,

Thanks for bringing up the emails, I just found those threads with Kate in our files. For reference, here's the raw data that we have.



Out of ecological curiosity, do you have a hypothesis for biomass higher in drought plots than controls in 2019? did dominant species shift or anything?

Thanks,
Tim

**Comment by tim-ohlert** [comment]
I do ... water is likely overrated as you move north, at least in the summer. Wind causes major changes to plant development, and the core treatment is an actual windbreak.  As you move to less water limited systems, the wind impacts likely swamp the water impacts.

Our field sites here are the literal northern edge of the great plains.  What is observed in CO and KS doesn't seem to be happening up here!

jc

**Comment by tim-ohlert** [comment]
To add JC's point, the usual suspects are root systems (e.g., root length, turnover) as dominant species remained the same in our grasslands during the experimental periods.

attached is the resulting publication for this experiment, where we've tested a few potential mechanisms and found little evidence.

Baka
