### ISSUE TITLE
Import Cover: Santa Cruz Low 2018, 2019

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#286]

**Comment by kristenpeach** [comment]
These cover values are decimal points similar to other Santa Cruz sites. I'd just like confirmation that I should multiply these values by 100 the same way I did the other decimal cover value sites.

**Comment by kristenpeach** [comment]
I am referring to Santa Cruz Low 2018 ^

**Comment by KW529** [comment]
Hi Kristen,

Yes, please multiply by 100. Thanks!

Best,

Kate Wilkins
Pronouns<https://www.mypronouns.org/what-and-why>: She/her(s)
PhD, Ecology
Postdoctoral Fellow
Department of Biology
Colorado State University
website: http://kate-wilkins.weebly.com/
phone: 713-819-1198
________________________________

**Comment by kristenpeach** [comment]
Santa Cruz Low 2018 done

**Comment by kristenpeach** [comment]
The cover file for Santa Cruz Low 2019 lacks a date (https://www.dropbox.com/preview/IDE_data_May%202018/Raw%20csv%20data/SantaCruzLow_ide%20data_2019_cover.csv?role=personal). There is a date column but it is blank.

**Comment by KW529** [comment]
**Sent 03-30-2021:**

Hi Michael,

What are the dates you all collected cover data for the Santa Cruz Low site in 2019? It would be great if you could update the attached file with this information if there are different dates for the plots. If it's one date, then you can just let me know.

Thanks so much!

Best,

Kate Wilkins

**Comment by KW529** [comment]
**From Michael Loik 03-30-2021:**

Hi Kate,

I am told it was 8 May 2019, and it should be the same date for all plots. 

One of my grad students noticed that the filename says "Santa Cruz Low", but on the spreadsheet itself, it says it is the Middle site. We thought we should note that to you.

Thanks,
Michael

**Comment by KW529** [comment]
**03-31-2021:**

Hi Michael,

Thanks for the update on the sampling date and for catching the incorrect site name. Could you confirm that this is the correct cover for Santa Cruz Low? The csv I sent previously was pulled from the 2019 spreadsheet you sent for Santa Cruz Low (see attached). 

Thanks!

Best,

Kate Wilkins

Michael's response:

Hi Kate,

Sorry for the confusion. After double-checking a few things today, I am convinced these are the Low elevation site data. Column A in the "Cover' tab is mis-labeled, possibly a copy-and-paste error.

Please let me know if there is anything else I can clarify. Sorry again for the confusion.

Best,
Michael

**Comment by KW529** [comment]
Sent 9-23-2021:

Hi Michael,

I took a quick peek at your files and found the following issues:

Santa Cruz High: the cover tab has 05-11-2019 listed as the date. Should this be 05-11-2021, or did you all accidentally place the 2019 cover data in this tab?

Santa Cruz Middle: In the cover tab, the date is missing for 55 rows. Should these say 05-13-2021 as the date?

Santa Cruz Low:  the cover tab has 04-26-2018 listed as the date. Should this be 04-26-2021, or did you all accidentally place the 2018 cover data in this tab?

Thanks so much for any clarification on this!

Best,

Kate Wilkins

**Comment by KW529** [comment]
Sent from Michael (9-23-2021):

Hi Kate,

Here are the sampling dates for 2021 for the Santa Cruz sites:

Low 5/5/21
Middle 5/13/21
High 5/11/21

Let me know if I can help with anything else.

Thanks!

Michael

**Comment by tim-ohlert** [comment]
Looks like this has been done
