### ISSUE TITLE
Import cover: Freiburg 2016-2017

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#288]

**Comment by KW529** [comment]
From: Wilkins,Kate <Kate.Wilkins@colostate.edu>
Sent: Wednesday, November 10, 2021 7:44 AM
To: Smith,Melinda <Melinda.Smith@colostate.edu>; tobias.gebauer@biologie.uni-freiburg.de <tobias.gebauer@biologie.uni-freiburg.de>; Peter Wilfahrt <wilf0020@umn.edu>
Subject: Re: IDE Update
 
Hi Tobias,

Thanks so much for sending this data. Could you please format your cover table like the attached datasheet? 

Best,

Kate Wilkins
[Pronouns](https://www.mypronouns.org/what-and-why): She/her(s)

**Comment by KW529** [comment]
Sent 04-21-2022:
Hi Tobias,

Would you mind reformatting your cover data (see attached cover template) per my last email in November?

I hope all is well, and please let me know if you have any questions!

Thanks,

Kate Wilkins

**Comment by tim-ohlert** [comment]
Peter reformatted and Tim entered
