### ISSUE TITLE
Import cover: Biddulph 2019-2020

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#298]

**Comment by KW529** [comment]
Hi Eric,

Thanks again for participating in DroughtNet, and I hope all is well! I am writing to see if you could update your taxa table for 2020 (see attached) to include information for the following plant codes found in the cover table:

ARTE CAM
CALA LON
CHEN ALB

Thanks so much!

Best,
Kate

**Comment by KW529** [comment]
New taxa table sent and now need to upload to My SQL

**Comment by tim-ohlert** [comment]
Looks like this is done
