### ISSUE TITLE
Import biomass: Sandhill 2018-2019

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#325]

**Comment by nutnetadmin** [comment]
Imported with import-sandhill-2019-2020.sql

Couldn't decide on how to handle pine needle biomass, so I created new category for it for paper PIs to decide

**Comment by KW529** [comment]
Hi Alyssa,

I'm back with two more questions regarding your sandhills site with Martin our weather data guru and Kate the all other things Drought-net guru in CC.

1) The Drought-net paper in the works is explicitly looking at ANPP. How well do you think your data represent ANPP, as opposed to standing biomass? I ask particularly because of the longleaf pines, as they can persist in the grass stage for some time. I suggested to Kate that we should not use the pine needle litter in the ANPP calculation. Do you think the living tissue harvested represents tissue grown in the plot that year?

2) Could you fill out the weather template attached? I looked at the weather data from NTN  and it looks like the precipitation data should work (attaching that here too for ease). I don't see temperature data but we're only using precip data so far in this manuscript so maybe it's okay to skip for now. The subppt column looks like the data we're looking for. Once you have it filled out, could you send it to Martin with a reminder that this is weekly data (not sure if this matters or not in your scripts Martin).

Let me know if any of this is unclear. Thanks!

Peter

**Comment by KW529** [comment]
Hey Peter,
The pine needle litter was from the mature overstory pines. I don't have many grass-stage longleaf pines at my site, and none that were in the clipped areas this year. I wouldn't think it should be counted as ANPP since it's not growing in the understory (I'm not sure how you typically handle overstory trees in plots!). I just think of the pine needles as litter that covers the soil surface and excludes light in the understory, but wanted to sort them out separately from 'litter' since I wasn't sure how the network handles this kind of overstory situation. The biomass of the pine needles does represent what was grown in that year from the overstory. Does this help with your first question? Should I sort things differently this year? 

Martin,
I will get that weather template to you ASAP!
Thanks,
Alyssa

**Comment by KW529** [comment]
Hi Alyssa,

I think having the needle litter is potentially valuable and also makes sense to have it separated from litter.

So we can probably safely assume that the live biomass collected at your site is a good representation of ANPP of the undergrowth since there were no baby longleaf pines harvested? Does that work for you Kate?

Thanks!
Peter
