### ISSUE TITLE
Import cover: Jilpanger 2017-2019

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#329]

**Comment by KW529** [comment]
Hi John,

Thanks so much for your participation in DroughtNet. I noticed that one species (Lagenophora stipitata) listed in your cover table in 2018 is missing from your taxa table. Would you mind filling out the information for this species in the attached taxa table? Thanks so much!

Best,
Kate

*NOTE: I found info on this species and added it to the database, but will double check with what John says

**Comment by KW529** [comment]
All data has been uploaded to the database, but waiting to hear back from John.

**Comment by tim-ohlert** [comment]
Looks like this is done
