### ISSUE TITLE
Import cover: Kiskunsag 2015-2018

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#334]

**Comment by KW529** [comment]
Dear Gyuri,

I hope this email finds you well! I am emailing to inquire about a species on your taxa table that has a mismatch in the genus species. In the taxa table under the taxa column, you have a species listed as 'CENTAUREA ARENARIA', however, in the species column for this taxa, the species is 'campestris'. Which is the correct name? 

Best,
Kate

*NOTE: Currently entered as _Centaurea arenaria_ because _Centaurea campestris_ not found in World Flora

**Comment by KW529** [comment]
Hi Gyuri,

In addition, you are missing a species on your 2018 taxa table. Could you please add information to the attached table on Erophila verna? Thanks!

Best,
Kate

*Currently have all but 2018 data entered

**Comment by KW529** [comment]
Sent 04-25-2022:

Hi Gyuri,

I am forwarding a series of messages I sent to you late last year, but it looks like I had an outdated email address. Here's a synopsis of the questions (also in previous e-mail's below):
In the taxa table (attached) under the taxa column, you have a species listed as 'CENTAUREA ARENARIA', however, in the species column for this taxa, the species is 'campestris'. Which is correct?
Could you please add information to the attached table on Erophila verna? 
Thanks!

Kate Wilkins
[Pronouns](https://www.mypronouns.org/what-and-why): She/her(s)
PhD, Ecology
Postdoctoral Fellow
Department of Biology
Colorado State University
website: http://kate-wilkins.weebly.com/
phone: 713-819-1198

Forwarded messages are above.

**Comment by tim-ohlert** [comment]
All except for 2018 was already done. Tm just did 2018
