### ISSUE TITLE
Import cover: Oklahoma 2016-2019

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#355]

**Comment by KW529** [comment]
Sent 02-07-2022:

Hi Lara,

Thanks so much again for submitting this data! I have also added Greg Newman to the email list. I am emailing because I have a few clarifying questions on your cover data (also attached).

2016: Could you please provide the full date for when you collected cover data (currently you only list year). 

2020: Could you provide the full date for the cover data (currently lists June 2020)? 

Thanks so much!

Best,

Kate Wilkins

**Comment by KW529** [comment]
Sent 02-07-2022:
Hi Mendy,

 

This site was only able to complete their early season cover survey in 2020. Should we include that data?

 

Best,

 Kate Wilkins

Mendy's reply: 

For now

Melinda D. Smith

**Comment by KW529** [comment]
Souza, Lara A. <lara.souza@ou.edu>
Mon 2/7/2022 12:54 PM
** Caution: EXTERNAL Sender **

hi Kate!

The specific dates for 2016 and 2020 are the following: 

2016: Cover was collected twice (May 19th/20th  and September 6/7th). The cover values we provided for 2016 were the "max" cover value for each species (often for forbs that value reflected May cover while grasses September cover).
2020: Foliar cover was collected June 29th and 30th 

Please let me know if you have any other questions!!
best, Lara

**Comment by KW529** [comment]
Sent 02-07-2022:
Hi Lara,

Thanks so much for these clarifications. For the 2016 cover, does it make sense to set all the dates for all species as Sept 6/7th since presumably forbs or early season grasses were checked again in the Fall? If not, could you please fill out the sheets I sent with the appropriate dates for each species?

Best,

Kate Wilkins

**Comment by KW529** [comment]
Sent 02-07-2022:
That is correct Kate. Setting Sep. 6/7th for 2016 is a good approach. 

best, Lara

Kate replied: Perfect- thanks, Lara!

**Comment by KW529** [comment]
Sent 03-21-2022:

Hi Lara,

Thanks again for the clarification on your dates. After diving into your cover data more, I found that information for the following species is missing from your taxa tables (please see taxa tables for the years with missing taxa attached):

date                    taxa 

2016-09-07        Forb_sp1 

2016-09-07        Forb_sp2 

2016-09-07        Koeleria_macrantha 

2017-08-01        Graminoid2 

2017-08-01        UnknownD22 

2017-08-01        UnknownD25 

2017-08-01        UnknownD29 

2019-08-01        d20 

2019-08-01        forb11 

2019-08-01        forb4 

2019-08-01        forb6 

2019-08-01        forb9 

2019-08-01        grass1 

2019-08-01        grass4 

2019-08-01        grass6 

2019-08-01        Grass_sp.(oklah.us) 

2019-08-01        sedge_sp.(oklah.us) 

2019-08-01        woody1_like 


Best,

Kate Wilkins

**Comment by KW529** [comment]
Sent 03-23-2022:

hi Kate, 
I reread your email and realized I misunderstood what you were asking (apologies).

From the taxa list you sent, we were not able to identify the unknows (e.g., Forb_sp1) to genus/species level. I am happy to fill out the taxa for the list of unknowns you sent us, but would only be able to provide information such as Kingdom, division, life form and psn (but missing information such as genus, species, life span, provenance, and local name). 

For Koeleria, I can have added the taxa information to the 2016 data (see attached). 

Let me know how to proceed with the unknows. Thanks!!
lara

**Comment by KW529** [comment]
03-23-2022:
Hi Lara,

No worries and thanks so much for adding Koeleria! Do you know the functional groups of unknowns D22, D25, and D29?

I can add the other unknowns to your taxa tables.

Best,

**Comment by KW529** [comment]
04-18-2022:

Hi Lara,

Just checking back on this email about the functional groups for the unknowns D22, D25, and D29.

Thanks!

Kate Wilkins

**Comment by KW529** [comment]
04-20-2021:
hi Kate!
I am copying Karen Castillioni here to see if she can help us with the unknowns below. I have looked at our spreadsheets and am unable to determine the functional group.

Karen, do you know if unknowns D22, D25 and D29 are forbs or graminoids? Those were collected in 2017 (see data below). I am thinking those could be forbs as they show up in our May surveys but not in our August Surveys (we measured plant composition two times in 2017 and provided the max cover across those two periods for the composition dataset we turned in). Unless they were grasses that were hard to ID in May and later were identified in August (although we would have switched the code for the grass name if that was the case).

best, Lara

**Comment by KW529** [comment]
04-21-2022:
Hi Kate,

It looks like these are unknown species, and no more information is provided about their functional group. Based on that, I can't tell with confidence to which group they belong.  

Best wishes,
Karen

**Comment by KW529** [comment]
P.S. Even if you don't know the genus of your other unknowns, could you please add them all to the attached taxa table? 

Thanks!

**Comment by KW529** [comment]
04-25-2022:

Here it is Kate. 
Let us know if any other information is needed. 

thanks!
lara

**Comment by KW529** [comment]
Hi Lara,

Perfect- thanks! I have another quick question regarding your plots. In 2016-2018, you all list plots 4, 5, 12, 13, 17, and 19. However, it looks like you added three new control plots (non-infrastructure) in 2019 and 2020 (plots 22, 23, and 24). Is this correct? Why did new plots appear in 2019 and 2020?

Thanks so much for any clarification.

Cheers,

Kate Wilkins

**Comment by KW529** [comment]
Hi -- I can answer that one. The structural control plots (22-24) were not part of the original design and we set those up in 2019 to start measuring control plots without a roof after recognizing differences in biomass under the rain-out shelters from the surrounding prairie. I'd be curious to see what shelter effects other sites have found and how it varies with size (both shelter square meter area and height). I now have some HOBO data that suggests a temperature and relative humidity effect of our shelters.

Best,
Greg

**Comment by tim-ohlert** [comment]
Looks like this is done
