### ISSUE TITLE
Import cover: Elva 2015-2021

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#366]

**Comment by KW529** [comment]
Hi Meelis,

Thanks again for sending us your IDE data. In your 2021 cover data, a new species appears (Phleum pratense), but this species does not appear in your taxa table. Could you please update the attached taxa table with this species?

Thanks so much!

Best,
Kate

**Comment by KW529** [comment]
Hi Kate,


Sorry for this mistake. Here is the new csv file and the whole excel workbook with corrected data.

Greetings,

Meelis

**Comment by KW529** [comment]
Updated files in IDE May 2018 folders

**Comment by tim-ohlert** [comment]
Looks like this is done
