### ISSUE TITLE
Import cover: Haveroya 2016-2019

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#376]
Hi Siri,

I hope all is well! I am now working on cleaning the plant species composition data and have a question about blank rows in the data for Haverøya and Store Buøya. For around 30 rows, there are blanks in the taxa column, but a cover value is listed (see attached). Should these rows be omitted or is there a species associated with these cover values?

Best,

Kate Wilkins

**Comment by KW529** [comment]
Also sent on 09-09-2021:

P.S. For Lygra Young (as an example) you list two cover values for multiple species (see example for Bryospida_sp below) in the same plot on the same date. Should I average these values, add them, or take the highest of the two?

site | block | plot | subplot | taxa | cover | date
-- | -- | -- | -- | -- | -- | --
Lygra_young | 1 | 1.1. | A | Bryopsida_sp | 1 | 7/24/2016
Lygra_young | 1 | 1.2. | A | Bryopsida_sp | 1 | 8/26/2017
Lygra_young | 1 | 1.2. | A | Bryopsida_sp | 2 | 7/24/2016
Lygra_young | 1 | 1.2. | A | Bryopsida_sp | 1 | 7/24/2016
Lygra_young | 2 | 2.1. | A | Bryopsida_sp | 1 | 7/28/2016
Lygra_young | 2 | 2.2. | A | Bryopsida_sp | 1 | 7/28/2016
Lygra_young | 3 | 3.1. | A | Bryopsida_sp | 1 | 7/29/2016
Lygra_young | 3 | 3.3. | A | Bryopsida_sp | 1 | 8/26/2017
Lygra_young | 3 | 3.3. | A | Bryopsida_sp | 1 | 7/29/2016
Lygra_young | 3 | 3.3. | A | Bryopsida_sp | 1 | 7/29/2016

In addition, one unknown herb species is listed 7 times in the same plot and date:

site | block | plot | subplot | taxa | cover | date
-- | -- | -- | -- | -- | -- | --
Lygra_young | 2 | 2.1. | A | Unknown_herb | 1 | 8/31/2017
Lygra_young | 2 | 2.1. | A | Unknown_herb | 1 | 7/28/2016
Lygra_young | 2 | 2.1. | A | Unknown_herb | 1 | 7/28/2016
Lygra_young | 2 | 2.2. | A | Unknown_herb | 8 | 7/28/2016
Lygra_young | 2 | 2.2. | A | Unknown_herb | 2 | 7/28/2016
Lygra_young | 2 | 2.2. | A | Unknown_herb | 1 | 7/28/2016
Lygra_young | 2 | 2.2. | A | Unknown_herb | 1 | 7/28/2016
Lygra_young | 2 | 2.2. | A | Unknown_herb | 2 | 7/28/2016
Lygra_young | 2 | 2.2. | A | Unknown_herb | 1 | 7/28/2016
Lygra_young | 2 | 2.2. | A | Unknown_herb | 1 | 7/28/2016
Lygra_young | 3 | 3.2. | A | Unknown_herb | 2 | 7/29/2016

</html>

**Comment by KW529** [comment]
Hi Kate,

Sorry for the delayed answer. These are independent observations on species we were not able to determine to species (normally due to very immature leaves). Duplicated recordings are separate species, but we were only able to determine them to the same taxonomic level. How to handle them in the analyses therefore depends on the question, but I guess the sum will be reasonable for everything not depending on species richness.

Please let me know if this is still unclear.

Best wishes,
Siri

**Comment by KW529** [comment]
Hi Siri,

Thanks for these clarifications. For the unknown species, it would be super helpful for our database if you could assign names (e.g. Unknown forb 1 or Unknown species 1) to these where there are currently blanks in the cover table and include these unknowns in your taxa table (even if you cannot fill out information for the family or genus). Please let me know if you have any questions about this!

Best,

Kate Wilkins

**Comment by KW529** [comment]
Hi Siri,

I am checking in to see if you've had a chance to assign names (e.g. Unknown forb 1 or Unknown species 1) to these where there are currently blanks in the cover table and include these unknowns in your taxa table (even if you cannot fill out information for the family or genus). 

Thanks so much!

Best,

**Comment by KW529** [comment]
Hi Kate,

I hope and believe that I have now corrected the missing taxa. I also realised that I slightly misunderstood some of your emails when reading them in-between other work, so apologies for possibly confusing answers. 

All cover rows with a 'cover' value should now also have information in the 'taxa' column. You can delete the rows that have blanks in both 'taxa' and 'cover'. I have double checked with the field sheet that these are in fact superfluous and not rows missing both taxa and cover. 

Best wishes,
Siri

**Comment by KW529** [comment]
Hi Siri,

I did notice one error. Your date for 2019 in the cover tab is written as: 2019-08-. Could you please provide the full date? You can just tell me and I will fill it in, unless different plots were sampled on different days.

Best,

**Comment by KW529** [comment]
Hi Siri,

I am checking in to see if you have the full date for the data you collected in 2019. Thanks!

Best,

**Comment by tim-ohlert** [comment]
Looks like this is done
