### ISSUE TITLE
Import cover: JRN, NNSS, OCTC (Sam's sites)

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#388]
Hi Sam,

Thanks again for all your work on this data! I have a quick question- are your cover values currently proportions instead of percent cover (i.e., should I multiply them by 100)?

Best,

Kate Wilkins

**Comment by KW529** [comment]
Kate

They are indeed proportions! Most sum to 100% but some plots are slightly over- we record overlapping plant canopies to 1cm resolution, so on productive years it can be a lot of cover.

Sam

**Comment by KW529** [comment]
Multiplied values by 100%

**Comment by KW529** [comment]
Hi Sam,

I have another quick question. For your NNSS Mojave site, you have duplicate values for Chorizanthe brevicornu (see table below) in the same plot and date. Should I add these values together, average them, or take the highest value? Thanks so much for any clarification!

site | block | plot | subplot | taxa | cover | date
-- | -- | -- | -- | -- | -- | --
NNSS_Mojave | NA | 101 | NA | Chorizanthe brevicornu | 0.00207 | 5/20/2020
NNSS_Mojave | NA | 101 | NA | Chorizanthe brevicornu | 0.003472 | 5/20/2020
NNSS_Mojave | NA | 105 | NA | Chorizanthe brevicornu | 0.008095 | 5/2/2019
NNSS_Mojave | NA | 105 | NA | Chorizanthe brevicornu | 0.00068 | 5/2/2019
NNSS_Mojave | NA | 107 | NA | Chorizanthe brevicornu | 0.043367 | 5/2/2019
NNSS_Mojave | NA | 107 | NA | Chorizanthe brevicornu | 0.002694 | 5/2/2019
NNSS_Mojave | NA | 115 | NA | Chorizanthe brevicornu | 0.004772 | 5/2/2019
NNSS_Mojave | NA | 115 | NA | Chorizanthe brevicornu | 0.000682 | 5/2/2019

**Comment by KW529** [comment]
Kate

I can only imagine the number of errors you turn up with the pile of data from the Net! I have included all of the info to fix the error, but let me know if you'd rather I do it and resubmit our data. 

I looked at the original data and I made the error formatting data to send to you. For all of the examples you highlighted, the smaller value in each case belongs to a different species in the same genus- Chorizanthe rigida. I found two other places where there are errors with this species:

Plot 119 in 2019 also has C. brevicornu listed twice, and C. rigida should be the lower value, 
Plot 117 in 2020 has only C. brevicornu listed but should be C. rigida

Here is the taxa information for that species, since it didn't end up on the taxa sheet:

Chorizanthe rigida, Devil's spineflower, Plantae, Magnoliophyta, Polygonaceae, Chorizanthe, rigida, NA, forb, annual, UK, NA, native

Just another tiny plant with spikes in the desert! Sorry for the trouble. I don't know yet how I made the mistake, so I don't know if I did this with other plots. If you see other duplicate species listed in the same plot (or anything that doesn't look right), feel free to reach out.

**Comment by KW529** [comment]
Hi Sam,

No worries- I haven't yet encountered a flawless dataset. It's my job to find and correct these things!

I started to make the corrections myself, but didn't see C. brevicornu listed in plot 119 (for 2019 or 2020) in the data you sent. Maybe it would be best for you to correct these numbers and send back the new datasheet. I will add the species details to the taxa table, so all I need is a new cover data sheet from you. The great news is that I didn't find any duplicate values in the JRN or OCTC data.

Also, what a cute plant! I eschew the common name Devil's spineflower in favor of adorable fuzzy spineflower.

Best,

Kate Wilkins

**Comment by KW529** [comment]
Sam sent updated cover table for NNSS. Added this to the Raw csv folder and corrected in the file under IDE data.

**Comment by tim-ohlert** [comment]
Looks like these were ultimately entered
