### ISSUE TITLE
Import cover: Sedgwick Reserve 2016-2018

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#408]
<html>
<body>
<div class="x_elementToProof" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Hi Dr. D'Antonio,</div><div class="x_elementToProof" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br aria-hidden="true"></div><div class="x_elementToProof" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I am emailing about the data you submitted as part of the International Drought Experiment for the<span> </span><span data-markjs="true" class="mark3t8a0euyy" data-ogac="" data-ogab="" data-ogsc="" data-ogsb="" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;">Sedgwick</span><span> </span>site. Thanks again for participating in the network! </div><div class="x_elementToProof" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br aria-hidden="true"></div><div class="x_elementToProof" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I have a few questions for you:</div><div class="x_elementToProof" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><ol><li><span style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;">I currently only have 2016 and 2017 data for your site. Do you have subsequent years of data?</span></li><li><span style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;">For your cover data, it looks like you all collected cover in different subplots for each plot. Should I treat these subplots as their own plots, or should I average values together at the plot level? See example below:</span></li></ol><div style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;"><span style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;"><div class="zVKDvDTqOz03RwzWfbOo" has-hovered="true" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit; position: relative; overflow: hidden; height: 46px; width: 426.5px;"><div class="UKD6MvPOV3wYwCjbc_Nx" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit; opacity: 0; z-index: -1; position: absolute;"><button type="button" class="ms-Button ms-Button--icon oD_UDPwB9iAnBEswdmii root-465" title="Show original size" aria-label="Show original size" data-is-focusable="true" style="margin: 0px; padding: 8px; border: none; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: controlIcons !important; vertical-align: baseline; color: var(--white); outline: transparent; position: absolute; -webkit-font-smoothing: antialiased; box-sizing: border-box; display: inline-block; text-decoration: none; text-align: center; cursor: pointer; border-radius: 2px; width: 32px; height: 32px; background: var(--neutralPrimary); user-select: none; top: 5px; z-index: 1; box-shadow: 0 0 5px var(--neutralSecondary); left: 5px;"><span class="ms-Button-flexContainer flexContainer-158" data-automationid="splitbuttonprimary" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit; display: flex; height: 16px; flex-wrap: nowrap; justify-content: center; align-items: center;"><i data-icon-name="FullScreen" aria-hidden="true" class="ms-Icon root-90 css-166 ms-Button-icon icon-160" style="display: inline-block; font-size: 16px; margin: 0px 4px; height: 16px; line-height: 16px; text-align: center; flex-shrink: 0; -webkit-font-smoothing: antialiased; font-style: normal; font-weight: normal; speak: none; font-family: controlIcons;"></i></span></button></div>

site | block | plot | subplot | taxa | cover | date | note_cover
-- | -- | -- | -- | -- | -- | -- | --
Sedgwick Reserve | NA | 1 | B | Avena_fatua | 1 | 4/28/2017 | NA
Sedgwick Reserve | NA | 1 | D | Avena_fatua | 3 | 4/28/2017 | NA

</div><br aria-hidden="true"></span></div><div style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;"><span style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;">Thanks so much for any clarification, and I hope you have a great weekend!</span></div><div style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;"><span style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;"><br aria-hidden="true"></span></div><div style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;"><span style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;">Best,</span></div></div><div style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 15px; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; vertical-align: baseline; color: rgb(32, 31, 30); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important;"><br aria-hidden="true"></div><div id="x_Signature" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;"><div style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;"><div style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;"></div><div style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;"></div><div id="x_divtagdefaultwrapper" dir="ltr" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important; background-color: rgb(255, 255, 255) !important;"><div style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: Tahoma; vertical-align: baseline; color: inherit;"><font face="Arial"><div style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;"></div><span id="x_ms-rterangepaste-start" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit;"></span><div style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: Arial; vertical-align: baseline; color: inherit;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: inherit; vertical-align: baseline; color: inherit;">Kate Wilkins</span></div></font></div></div></div></div></div>
</body>
</html>

**Comment by tim-ohlert** [comment]
Ok, so I just made all the D subplots new plots. It's not a perfect solution but it worked
