### ISSUE TITLE
Import biomass: Sedgwick 2016-2018

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#409]
Uploaded 2016-2017 biomass, need to upload 2018. 

I currently only have 2016-2018 data for your site. Do you have subsequent years of data? Original email sent 03-25-2022. Followed up on 04-18-2022

**Comment by KW529** [comment]
Only 2016-2018 data available.

**Comment by KW529** [comment]
RE: MAP for Sedgwick (original email at bottom):

08-12-2022 from Carla: wow well that was a mistake.   it must have been a mistake upon entry by my former technician. I wonder if she was reporting the amount for that particular year as opposed to a mean over time?   i'm so sorry about that. it needs to be fixed. at least it isnt off by an order of magnitude.   i'm sorry to mess up everyone's regressions but 380 mm is a number previously published by nutnet folks, schimel lab people whose site is right near the IDE site and old Seabloom papers (also same area). can you please change this number in the main files there? thank you. 

Carla
On Fri, Aug 12, 2022 at 3:10 PM Wilkins,Kate <[Kate.Wilkins@colostate.edu](mailto:Kate.Wilkins@colostate.edu)> wrote:
Hi Carla,

The 303 mm MAP is what your site reported to us in the original datasheets for 2016-2018 (see attached) under the site tab in the precip column. 

The MAP we use in the manuscript for all sites is site-reported.

Best,

Kate Wilkins
[Pronouns](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.mypronouns.org%2Fwhat-and-why&data=05%7C01%7CKate.Wilkins%40colostate.edu%7C85b03da39f654a75756908da7cb241e7%7Cafb58802ff7a4bb1ab21367ff2ecfc8b%7C0%7C0%7C637959402304534666%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UzbF27%2Fm0ydfZdxkNyjg%2Bhhz2FvOaymso%2Bi3n2IgWdI%3D&reserved=0): She/her(s)
PhD, Ecology
Postdoctoral Fellow
Department of Biology
Colorado State University
website: [http://kate-wilkins.weebly.com/](https://nam10.safelinks.protection.outlook.com/?url=http%3A%2F%2Fkate-wilkins.weebly.com%2F&data=05%7C01%7CKate.Wilkins%40colostate.edu%7C85b03da39f654a75756908da7cb241e7%7Cafb58802ff7a4bb1ab21367ff2ecfc8b%7C0%7C0%7C637959402304534666%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pAujoqnhturt4Cmtn%2Fizyv8mzPl66Qp2f72kMrISSwQ%3D&reserved=0)
phone: 713-819-1198
From: Carla D'Antonio <[dantonio@es.ucsb.edu](mailto:dantonio@es.ucsb.edu)>
Sent: Monday, July 25, 2022 12:30 PM
To: Wilkins,Kate <[Kate.Wilkins@colostate.edu](mailto:Kate.Wilkins@colostate.edu)>
Subject: Re: IDE Manuscript: Final PNAS Draft
 
** Caution: EXTERNAL Sender **

the published numbers for sedgwick MAP that i have seen are 380, 397, and 500.  this raises a bigger question about making sure your MAP values are accurate for the many many sites. 

fyi in the author list my zip code is listed as 93105 but it is 93106. very minor. 

Carla

**Comment by tim-ohlert** [comment]
2018 entered
