### ISSUE TITLE
Import biomass: Freiburg 2018-2020

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#412]

**Comment by KW529** [comment]
Sent: 04-21-2022

Hi Tobias,

Would you mind reformatting your cover data (see attached cover template) per my last email in November?

I hope all is well, and please let me know if you have any questions!

Thanks,

Kate Wilkins

From: Wilkins,Kate <Kate.Wilkins@colostate.edu>
Sent: Wednesday, November 10, 2021 7:44 AM
To: Smith,Melinda <Melinda.Smith@colostate.edu>; tobias.gebauer@biologie.uni-freiburg.de <tobias.gebauer@biologie.uni-freiburg.de>; Peter Wilfahrt <wilf0020@umn.edu>
Subject: Re: IDE Update
 
Hi Tobias,

Thanks so much for sending this data. Could you please format your cover table like the attached datasheet? 

Best,

Kate Wilkins
[Pronouns](https://www.mypronouns.org/what-and-why): She/her(s)
PhD, Ecology
Postdoctoral Fellow
Department of Biology
Colorado State University
website: http://kate-wilkins.weebly.com/
phone: 713-819-1198
From: Smith,Melinda <Melinda.Smith@colostate.edu>
Sent: Wednesday, November 10, 2021 7:30 AM
To: tobias.gebauer@biologie.uni-freiburg.de <tobias.gebauer@biologie.uni-freiburg.de>; Wilkins,Kate <Kate.Wilkins@colostate.edu>; Peter Wilfahrt <wilf0020@umn.edu>
Subject: RE: IDE Update
 
Many thanks!

 

From: Tobias Gebauer <tobias.gebauer@biologie.uni-freiburg.de>
Sent: Wednesday, November 10, 2021 6:40 AM
To: Wilkins,Kate <Kate.Wilkins@colostate.edu>; Peter Wilfahrt <wilf0020@umn.edu>
Cc: Smith,Melinda <Melinda.Smith@colostate.edu>
Subject: Re: IDE Update

 

Hi Kate, Menda and Peter,

hope this email finds you well.

I am very sorry for the delay...

Attached you find cover, biomass and climate data for the Freiburg site.

 

Greetings,

Tobi

**Comment by tim-ohlert** [comment]
Re-entered all biomass data back to 2016. Removed exclosures and nutnet plots
