### ISSUE TITLE
Import biomass: Noor 2019

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#417]
Hi Mehdi,

I hope all is well, and thanks so much again for sharing your data with DroughtNet. Could you please provide the full date of when you first started the drought treatments? Currently, you all just list the year (2017).

Thanks so much!

Cheers,

Kate Wilkins

**Comment by KW529** [comment]
Hi Kate,
Hope you are doing well.
The starting time of the project was 7/17/2017. We also started recording soil temperature on 7/19/2017. 
Do you have any news from the first manuscript that was planned for PNAS? 
Best wishes,
Mehdi

**Comment by KW529** [comment]
Hi Mehdi,

Thanks so much! We are working on editing the manuscript and hope to submit it within the next few weeks.

Just to make sure I understand, did you all start the drought on 07-17-2017?

Thanks!

Best,

Kate Wilkins

**Comment by KW529** [comment]
Hi Kate,
Yes, it is correct. 7/17/2017.
I had photos of starting project and establishing shelters and then double checked the exact time from photo properties to be sure.

Best wishes,
Mehdi

**Comment by KW529** [comment]
Hi Mehdi,

Hopefully this is the last question. I noticed that the plots you all sample biomass from have different areas. Did you scale the biomass to g/m^2 before sending it? Also, should I average the subplots submitted within each plot?

Thanks!

Best,

Kate Wilkins

**Comment by KW529** [comment]
Hi Kate,
Please find the following the answers:

On Thu, Jun 2, 2022 at 12:45 AM Wilkins,Kate <[Kate.Wilkins@colostate.edu](mailto:Kate.Wilkins@colostate.edu)> wrote:
Hi Mehdi,

Hopefully this is the last question. I noticed that the plots you all sample biomass from have different areas.
Yes, but precisely meaured. 
Did you scale the biomass to g/m^2 before sending it?
**Yes it is g/m2. but the value is g in each subplot. I mean I didn't change it to 1m2. If you need g/1m2 you can rescale the values according to the plot area.** 
Also, should I average the subplots submitted within each plot?
**Yes, you can. we have 2 subplots (A,B). then you can get the average of these two subplots for each plot.**
Thanks!
Best wishes,
Mehdi

**Comment by KW529** [comment]
Note from Kate: I scaled the biomass in the Excel spreadsheet since every plot had a different size (preserved their original ANPP values). They don't need any zero-filling since each functional group appears in each plot and iteration. I will average the iterations (subplots) in SQL.

**Comment by tim-ohlert** [comment]
Kate finished this a while ago
