### ISSUE TITLE
Import cover: Torla/Ordessa 2016-2019

### ISSUE THREAD

**Issue by tim-ohlert** [felt0134/drought-net-tickets#429]

**Comment by tim-ohlert** [comment]
Cover values are reported by Daubenmeier cover class, an ORDINAL variable. Though this data could potentially be used for species richness, it should not be used for measures such as evenness or rank abundance. Since the database does not currently have a way of curating ordinal data, cover data for this site has not been entered.

The following documents Tim's correspondence with site P Concepcion Alados

TIM:
Hello Concepción,

I am curating the cover data you submitted from your Torla.es Drought Network experiment and have a follow-up question. The submitted cover data shows percent cover based upon a categorical cover class (example data shown below). Are these data derived from a continuous percent cover values such that cover may be 1, 2, or 3 and so on? If so, that data would be helpful for calculating metrics such as rank abundance and community evenness.


CONCEPCION:
Hi Tim, Daubermier cover class is a rank order where 1 = cover lower than 1%
2= Cover < 5 %; 3 = cover < 15…. etc. so the cover is the half of the rank . That is 0.5  for the first order.

The rank I used is the column Cover Daubermier, next column is the half value of the rank that is as you estimate the continuous cover. 

I hope to be helpful

**Comment by ingridslette** [comment]
Issues that we should maybe contact the site about: 

Several species that are in the cover data are missing from the taxa file:
Allium_sp., Botrychium_lunaria, Buxus_sp., Centaurea_sp.3, Gentiana_cruciata, Hieracium_pilosella, Leontodon_pyrenaicum, Mentha_sp., Oxalis_sp., Prunella_grandiflora, Stachys_recta

Also, the info provided in the 'lifespan' column appears to actually be 'lifeform' info.
