### ISSUE TITLE
Falls.au Fixed MAP value

### ISSUE THREAD

**Issue by KW529** [felt0134/drought-net-tickets#445]

**Comment by KW529** [comment]
Mendy email 1/20/2022:

Hi John,

We are working on the revision of the IDE 1-year manuscript for Science and realized that there may be an issue with the MAP that you reported for the falls.au site. The amount that you reported for that site to us is 2366mm. However, when we look at the CHIRPS MAP value, it is 1328mm. With this mismatch, this creates an issue with calculating drought severity given that we have to use the CHIRPS derived annual precipitation. Can you please confirm if the value you reported is correct? Or does it includes snow? Thanks for your help with this. It would be great to get this resolved as soon as possible given that Kate is trying to finalize the analyses by Monday.

Best,

Mendy

**Comment by KW529** [comment]
John Morgan response:

I will check later today. That value includes snow no doubt. Do you want growing season precipitation?

**Comment by KW529** [comment]
Mendy response:
We want mean annual precipitation - thanks for checking!

Melinda D. Smith

**Comment by KW529** [comment]
John response:
This is the precipitation from the nearest station tom the experimental site = 1239mm.

I must have inadvertently mistyped the MAP - sorry!!! That makes a big difference

Best of wishes, JOHN

**Comment by KW529** [comment]
Kate reply:

So it looks like we should use their MAP. This will make the methods section less convoluted

**Comment by KW529** [comment]
Everyone agreed

**Comment by KW529** [comment]
MAP corrected in Site_Elev_Disturb file used in the year 1 manuscript code. @tim-ohlert will correct the value in SQL. MAP updated from 2366 mm to 1239 mm

**Comment by tim-ohlert** [comment]
Tim Ohlert changed this value in the sites table (SQL)
