### ISSUE TITLE
Import Pineta 2016-2017

### ISSUE THREAD

**Issue by felt0134** [felt0134/drought-net-tickets#5]
AJF.

**Comment by felt0134** [comment]
Had to clear all contents int he lifespan name because SQL didn't like the "hemi' name which contained " ' " kept causing problems

**Comment by felt0134** [comment]
Cover data:
#lots of mismatches in the taxa and cover species lists...need to fix
update cover_temp_ajf set  taxa = 'Gymandenia_conopsea' where taxa in ('Gymandenia_conopsea_', 'Gymnadenia_conopsea_(Noleopardo)');
update cover_temp_ajf set  taxa = 'Festuca_rubra' where taxa in ('Festuca_rubra_');
update cover_temp_ajf set  taxa = 'Carex_sp.' where taxa in ('Carex_sp');
update cover_temp_ajf set  taxa = 'Prunella_sp.' where taxa in ('Prunella');
update cover_temp_ajf set  taxa = 'Laserpitium_sp.' where taxa in ('Laserpitium');
update cover_temp_ajf set  taxa = 'Astrantia_major' where taxa in ('Astrantia_major_(NoRanunculus)');
update cover_temp_ajf set  taxa = 'Aquilegia_sp.' where taxa in ('Aquilegia_/Thalictrum');
update cover_temp_ajf set  taxa = 'Ranunculus_sp.' where taxa in ('Ranunculus');

**Comment by felt0134** [comment]
The removal of hemi removed the ability to add lifespans column on this site

**Comment by felt0134** [comment]
No clue what 'grande' and 'fresno' are referring to in taxa name...need to e-mail PI

**Comment by nutnetadmin** [comment]
It looks like we *may* have deleted some taxa around line 504 of import-pineta-2015.sql
Kate Wilkins is working on a fix for a similar issue for #2 (Aalmend-Brachy-2015).
This is @nutnetadmin 's fault 🥇
