### ISSUE TITLE
Import Naqu 2017-2018 biomass

### ISSUE THREAD

**Issue by pawilfahrt** [felt0134/drought-net-tickets#85]
Species specific biomass imported. Taxa table incomplete. Functional groups assigned.

**Comment by tim-ohlert** [comment]
Hi Juntao,

It would be great to know in particular whether that outlier in 2021 for the drought treatment is real or potentially a mistake?

Thanks,

Mendy

**Comment by tim-ohlert** [comment]
Dear Mendy and Tim,

I checked the initial weighing data and indeed this plot has a relatively large biomass. No calculation or upload errors. This could be the result of human error during sampling.

Thank you for letting us know about this issue.

 

Best wishes,

Juntao

**Comment by tim-ohlert** [comment]
We may want to consider dropping this rep -given they think it could be human error

-Mendy
